### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by traversaro**
Thanks @Tobias-Fischer, I did not even noticed that imgui was added to conda-forge.
I added Windows support as we are going to need it in https://github.com/conda-forge/dartsim-feedstock/issues/26 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I added myself as a maintainer to help debug eventual Windows issue.

**Comment by traversaro** [comment]
I also added some fixes related to the installation of `CMakeLists.txt` .

**Comment by Tobias-Fischer** [comment]
Looks great, thanks @traversaro!

**Comment by Tobias-Fischer** [comment]
PS: should I ping you in future requests to add recipes, and ask if you’d like to add Windows compatibility? I typically skip it to be honest ..

**Comment by traversaro** [comment]
> PS: should I ping you in future requests to add recipes, and ask if you’d like to add Windows compatibility? I typically skip it to be honest ..

No problem, if I just need the Windows compatibility in a recipe, I look if the recipe exists and add it. If I never look for it, then it is clear I do not need it, so skipping Windows is fine.

**Comment by traversaro** [comment]
fyi @S-Dafarra now `imgui` is on conda-forge, and you can use it with a standard `find_package(imgui REQUIRED)` and `target_link_libraries(... imgui::imgui)`. We could also add a `.pc` file for consistency with debian/ubuntu (https://packages.debian.org/sid/amd64/libimgui-dev/filelist), but I guess we can worry about this if we start actually using imgui in a robotology-superbuild-included project.

**Pull request merged**
